; TheNetNode Configuration File
;
; DO NOT CHANGE THE ORDER OF THE CONFIGURATION LINES !
; DO NOT CLEAR ANY LINES !
;
; NET/ROM-Sysop-Password, 80 Characters (01234567890123...)
12345678901234567890123456789012345678901234567890123456789012345678901234567890
;
; Console Password
Geheim
;
; Node Ident (Test)
Test  
;
; Node MyCall (XX0XX)
XX0XX
;
; Workpath, Path to the Help-Files ()
; TNN should be started from this path.
C:\tnn\14_5_15\179cb53\os\win32\tnn32\
;
; Path to the executable Text-Files (TEXTCMD\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\TEXTCMD\
;
; Path to the extern Programs for User (USEREXE\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\USEREXE\
;
; Path to the extern Programs only for Sysop (SYSEXE\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\SYSEXE\
;
; Path to the PACSAT-Files (PACSAT\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\PACSAT\
;
; Path fuer HTML (HTTPD\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\HTTPD\
;
; Path fuer SPEECH-File (SPEECH\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\SPEECH\
;
; Path fuer MSG-File (MSG\)
C:\tnn\14_5_15\179cb53\os\win32\tnn32\MSG\
